name: Run Python Tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run PyLint
        run: |
          pylint ./portfo
      - name: Run tests with pytest
        run: | 
          pytest -rf -x --junitxml=report.xml tests.py

